#!/bin/bash

thePort=8081

case $1 in
up*)
    echo "Starting boot2docker"
    boot2docker up
    echo "Checking inventorium database"
    db_name=`docker-compose ps | grep inventorium_database | cut -f 1 -d ' '`

    if [ -z $db_name ]
    then
        echo "Starting database..."
        docker-compose run -d database
        db_name=`docker-compose ps | grep inventorium_database | cut -f 1 -d ' '`
        echo "Database started with name $db_name"
    else
        echo "Database already started with name $db_name"
    fi

    # Get the container ID of the database
    db_container_id=`docker ps | grep inventorium_database | cut -f 1 -d ' '`
    if [ -z $db_container_id ]
    then
        echo "Something went horribly awry!"
    else
        echo "Starting API server, linking to database image with id $db_container_id"
    fi

    docker run \
        -p $thePort:$thePort \
        -itv `pwd`/site/:/opt/server \
        -e "HOST=0.0.0.0" \
        -e "DBHOST=database" \
        -e "DBPORT=5432" \
        -e "DBUSER=postgres" \
        -e "DBDATABASE=postgres" \
        -e "PORT=$thePort" \
        --link $db_container_id:database \
        zachmay/inventorium-api /bin/bash
    ;;
down*)
    echo "Halting boot2docker"
    boot2docker down
    ;;
esac
