#!/bin/bash

thePort=8081

case $1 in
up*)
    echo "Starting boot2docker"
    boot2docker up
    echo "Checking inventorium database"
    db_name=`docker-compose ps | grep inventorium_database | cut -f 1 -d ' '`

    if [ -z $db_name ]
    then
        echo "Starting database..."
        docker-compose run -d database
        db_name=`docker-compose ps | grep inventorium_database | cut -f 1 -d ' '`
        echo "Database started with name $db_name"
    else
        echo "Database already started with name $db_name"
    fi

#    docker run \
#        -p $thePort:$thePort \
#        -itv `pwd`/site/:/opt/server \
#        -e "HOST=0.0.0.0" \
#        -e "DBHOST=database" \
#        -e "DBPORT=5432" \
#        -e "DBUSER=postgres" \
#        -e "DBDATABASE=postgres" \
#        -e "PORT=$thePort" \
#        --link 2eb75ad0d74f:database \
#        zachmay/inventorium-api /bin/bash
    ;;
down*)
    echo "Halting boot2docker"
    boot2docker down
    ;;
esac
