#!/bin/bash

command="psql --host=$DBHOST --port=$DBPORT --username=$DBUSER --dbname=$DBDATABASE"

echo $command;

case $1 in
    console)
        $command
        ;;
    seed)
        echo "Seeding database $DBDATABASE on $DBHOST:$DBPORT as $DBUSER"
        $command <<EOSQL
truncate table "building" cascade;
truncate table "item_type" cascade;
truncate table "user" cascade;

insert into building (id, name, description, created, updated) values
    (1, 'Institute, Building A, The', '101 E. West St., Toronto', '2015-10-16 12:00:00', '2015-10-16 12:00:00'),
    (2, 'The Institute, Building B',  '103 E. West St., Toronto', '2015-10-17 12:00:00', '2015-10-17 12:00:00'),
    (3, 'Ministry of Truth, Annex 1', '4 BB Circle, London',      '2015-10-17 12:00:00', '2015-10-17 14:32:00');
alter sequence building_id_seq restart with 4;

insert into room (id, building, name, description, created, updated) values
    (1, 1, '202',      'Russell',          '2015-03-03 12:00:00', '2015-10-01 12:00'),
    (2, 1, '203',      'Whitehead',        '2015-02-02 12:00:00', '2015-10-02 12:00'),
    (3, 1, '204',      'Wittgenstein',     '2015-01-01 12:00:00', '2015-10-03 12:00'),
    (4, 3, 'Room 101', 'Interview Room 1', '1984-04-01 12:00:00', '2015-10-21 12:00');
alter sequence room_id_seq restart with 5;

insert into item_type (id, name) values
    (1, 'Desktop Computer'),
    (2, 'Laptop Computer'),
    (3, 'Projector'),
    (4, 'Tablet');
alter sequence item_type_id_seq restart with 5;

insert into item (id, name, serial_number, funding_source, item_type) values
    (1, 'Dell 101',        'ABC123',  'Grant 1', 1),
    (2, 'Dell 101',        'ABC124',  'Grant 1', 1),
    (3, 'Dell 101',        'ABC125',  'Grant 2', 1),
    (4, 'Macbook Pro',     'ZZZ001',  'Grant 1', 2),
    (5, 'Macbook Pro',     'ZZZ002',  'Grant 2', 2),
    (6, 'Super Projector', '1010101', 'Grant 1', 3);
alter sequence item_id_seq restart with 7;

insert into "user" (id, email, name, password) values
    (1, 'zach@uky.edu', 'Zachary May', 'abc123'),
    (2, 'test@test.com', 'Chuck Testa', 'chuck');
alter sequence user_id_seq restart with 3;

insert into check_in (id, item, room, date, "user" ) values
    (1, 1, 1, '2015-10-21 15:54:00', 1),
    (2, 1, 2, '2015-10-21 18:16:23', 2),
    (3, 1, 2, '2015-10-21 19:16:23', 2),
    (4, 2, 4, '2015-10-20 12:13:14', 1);
alter sequence user_id_seq restart with 5;

UPDATE item
SET current_check_in = (
    SELECT c1.id
    FROM check_in c1
    LEFT OUTER JOIN check_in c2 ON (c2.item = item.id AND c1.date < c2.date)
    WHERE c1.item = item.id AND c2.id IS NULL
);

EOSQL
;;
*)
    echo "Usage: db [console|seed]"
    echo "console: Run the Postgresql console."
    echo "seed:    Run the seeding script. Requires initial database migrations to have been run."
    ;;
esac

