#!/bin/bash

command="psql --host=$DBHOST --port=$DBPORT --username=$DBUSER --dbname=$DBDATABASE"

echo $command;

case $1 in
    console)
        $command
        ;;
    seed)
        echo "Seeding database $DBDATABASE on $DBHOST:$DBPORT as $DBUSER"
        $command <<EOSQL
truncate table building cascade;
truncate table item_type cascade;

insert into building (id, name, description, created, updated) values
    (1, 'Institute, Building A, The', '101 E. West St., Toronto', '2015-10-16 12:00:00', '2015-10-16 12:00:00'),
    (2, 'The Institute, Building B',  '103 E. West St., Toronto', '2015-10-17 12:00:00', '2015-10-17 12:00:00'),
    (3, 'Ministry of Truth, Annex 1', '4 BB Circle, London',      '2015-10-17 12:00:00', '2015-10-17 14:32:00');
alter sequence building_id_seq restart with 4;

insert into room (id, building, name, description) values
    (1, 1, '202', 'Russell'),
    (2, 1, '203', 'Whitehead'),
    (3, 1, '204', 'Wittgenstein'),
    (4, 3, 'Room 101', 'Interview Room 1');
alter sequence room_id_seq restart with 5;

insert into item_type (id, name) values
    (1, 'Desktop Computer'),
    (2, 'Laptop Computer'),
    (3, 'Projector'),
    (4, 'Tablet');
alter sequence item_type_id_seq restart with 5;

insert into item (id, name, serial_number, funding_source, item_type) values
    (1, 'Dell 101',        'ABC123',  'Grant 1', 1),
    (2, 'Dell 101',        'ABC124',  'Grant 1', 1),
    (3, 'Dell 101',        'ABC125',  'Grant 2', 1),
    (4, 'Macbook Pro',     'ZZZ001',  'Grant 1', 2),
    (5, 'Macbook Pro',     'ZZZ002',  'Grant 2', 2),
    (6, 'Super Projector', '1010101', 'Grant 1', 3);
alter sequence item_id_seq restart with 7;

EOSQL
;;
*)
    echo "Usage: db [console|seed]"
    echo "console: Run the Postgresql console."
    echo "seed:    Run the seeding script. Requires initial database migrations to have been run."
    ;;
esac

